version: '3.1'

services:

  university-application:
    build: .
    environment:
      - DATA_SOURCE_NAME=jdbc:postgresql://postgres:5432/university_db
    ports:
      - "8888:8080"
    networks:
      - network

  postgres:
    image: postgres:15.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../university-data/src/main/resources/sql/schema.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ../university-data/src/main/resources/sql/data.sql:/docker-entrypoint-initdb.d/fill_tables.sql
    environment:
      POSTGRES_DB: university_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5555:5432
    restart: always
    networks:
      - network

volumes:
  postgres_data:

networks:
  network:
    driver: bridge