version: '3.1'

services:

  tomcat-server:
    build: .
    restart: always
    ports:
      - "8080:8080"
    networks:
      - my-network

  postgres:
    image: postgres:15.2-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
      - ../university-data/src/main/resources/sql/schema.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ../university-data/src/main/resources/sql/data.sql:/docker-entrypoint-initdb.d/fill_tables.sql
    environment:
      POSTGRES_DB: university_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5050:5432
    restart: always
    networks:
      - my-network

volumes:
  postgres:

networks:
  my-network:
    driver: bridge