version: '3.1'

services:
  db:
    image: postgres:15.2-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./src/main/resources/sql/schema.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./src/main/resources/sql/data.sql:/docker-entrypoint-initdb.d/fill_tables.sql
    environment:
      POSTGRES_PASSWORD: 1111
      POSTGRES_USER: postgres
      POSTGRES_DB: university_db
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5050:5432
    restart: unless-stopped

volumes:
  postgres:
